name: Nightly Test run (Jahia Snapshot)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  integration-tests:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: site-settings-seo
      testrail_project: SEO Module
      pagerduty_incident_service: site-settings-seo-JahiaSN
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: site-settings-seo
      module_branch: ${{ github.ref }}
