name: Nightly Test run (Jahia Release)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  integration-tests:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee:8
      module_id: site-settings-seo
      testrail_project: SEO Module
      pagerduty_incident_service: site-settings-seo-JahiaRL
      provisioning_manifest: provisioning-manifest-release.yml
      artifact_prefix: site-settings-seo
      module_branch: ${{ github.ref }}
